import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import path from "path";
import fs from "node:fs";

// Try to read build info generated by scripts/generate-build-info.js
let buildInfo: { version?: string; gitHash?: string } | undefined;
try {
  const p = path.resolve(__dirname, "public", "build-info.json");
  if (fs.existsSync(p)) {
    const raw = fs.readFileSync(p, "utf8");
    buildInfo = JSON.parse(raw);
  }
} catch {
  // ignore parse errors and fall back
}

// Fallbacks are simple "??" if not available
const appVersion = (buildInfo?.version ?? "??") as string;
const gitCommit = (buildInfo?.gitHash ?? "??") as string;

export default defineConfig({
  plugins: [vue()],
  define: {
    __APP_VERSION__: JSON.stringify(appVersion),
    __GIT_COMMIT__: JSON.stringify(gitCommit),
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  server: {
    port: 5173,
    host: true,
    allowedHosts: ["local.local", "localhost"],
    proxy: {
      "/api": {
        target: "http://localhost:8080",
        changeOrigin: true,
      },
    },
  },
});
