-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgWq+gdlSkUKzIBiuI
Z7xVq8wjKwmNwpySBki8OBV29GugCgYIKoZIzj0DAQehRANCAARxH0/mfmlRaPXm
H4UAdElArfH263b3SAK/JYf+HgZbc3lWBMaGqI0ZqU6yXXavJ3D+EgPUdyWt7cMn
YI8MLxBc
-----END PRIVATE KEY-----
