{{- if .Values.monitoring.jobsMetrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "photo-upload.backend.fullname" . }}
  labels:
    {{- include "photo-upload.backend.labels" . | nindent 4 }}
    {{- with .Values.monitoring.jobsMetrics.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "photo-upload.backend.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: management
      path: /actuator/prometheus
      interval: {{ .Values.monitoring.jobsMetrics.interval | default "30s" }}
{{- end }}
