apiVersion: v1
kind: Secret
metadata:
  name: {{ include "photo-upload.fullname" . }}-secret
  labels:
    {{- include "photo-upload.labels" . | nindent 4 }}
type: Opaque
data:
  database.user: {{ .Values.database.external.user | b64enc | quote }}
  database.password: {{ .Values.database.external.password | b64enc | quote }}
  {{- if .Values.objectStorage.enabled }}
  objectStorage.accessKey: {{ required "objectStorage.accessKey is required when objectStorage.enabled" .Values.objectStorage.accessKey | b64enc | quote }}
  objectStorage.secretKey: {{ required "objectStorage.secretKey is required when objectStorage.enabled" .Values.objectStorage.secretKey | b64enc | quote }}
  {{- end }}
